name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Prepare code
        uses: actions/checkout@v3

      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install packages
        run: npm ci
        working-directory: ./server-api

      - name: Run tests
        run: npm run test
        working-directory: ./server-api