name: Run E2E Tests

on: [push]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: desafio-luizalabs-postgres

    steps:
      - name: Prepare code
        uses: actions/checkout@v3

      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: npm install
        working-directory: ./server-api

      - name: Run Tests
        run: npm run test:e2e
        working-directory: ./server-api
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/desafio-luizalabs-postgres?schema=public"